export const postConstants = {

  POST_LIKE_REQUEST: "POST_LIKE_REQUEST",
  POST_LIKE_SUCCESS: "POST_LIKE_SUCCESS",
  TIMELINE_GET_REQUEST: "TIMELINE_GET_REQUEST",
  TIMELINE_GET_SUCCESS: "TIMELINE_GET_SUCCESS",
};

export const commentConstants = {

  COMMENT_GET_REQUEST: "COMMENT_GET_REQUEST",
  COMMENT_GET_SUCCESS: "COMMENT_GET_SUCCESS",
};
